version: '3'
volumes:
  whisperdata:
    external: true  # Uses externally created volume

services:
  init-dummydata:
    image: python:3.11
    volumes:
      - whisperdata:/data
    working_dir: /data
    command: >
      bash -c "
      set -e
      echo 'Creating dummy dataset directory...'
      mkdir -p /data/whisper-dummy && cd /data/whisper-dummy

      echo 'Downloading sample mp3...'
      curl -L https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3 --output sample1.mp3

      echo 'Copying to sample2 and sample3...'
      cp sample1.mp3 sample2.mp3
      cp sample1.mp3 sample3.mp3

      echo 'Creating transcript file...'
      echo -e 'sample1.mp3|Hello world\nsample2.mp3|Welcome to Whisper\nsample3.mp3|Testing transcription' > transcripts.txt

      echo 'Dummy dataset setup complete.'
      "
    restart: "no"
